### ISSUE TITLE
Problems with virksomhetssertifkat

### ISSUE THREAD

**Issue by tofiksa** [digipost/signature-api-client-java#106]
Hei, har fått utstedt et testvirksomhetssertifikat av commfides med følgende keyusage og extended keyusage:

```
Owner: C=NO, L="Pilestredet 46, 0167 Oslo", O=OSLOMET - STORBYUNIVERSITETET - 997058925, OID.2.5.4.97=NTRNO-997058925, OU=Avdeling IKT/OsloMet, SERIALNUMBER=997058925, CN=OSLOMET - STORBYUNIVERSITETET
Issuer: C=NO, O=Commfides Norge AS - 988 312 495, OU=CPN Enterprise-Norwegian SHA256 CA- TEST, OU=Commfides Trust Environment(C) 2014 Commfides Norge AS - TEST, CN=Commfides CPN Enterprise-Norwegian SHA256 CA - TEST

#6: ObjectId: 2.5.29.37 Criticality=false
ExtendedKeyUsages [
  clientAuth
  emailProtection
  serverAuth
]

#7: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  DigitalSignature
]
```

og får slike feilmeldinger:

```
<pre>javax.servlet.ServletException: no.digipost.signature.client.core.exceptions.SignatureException: Unable to perform SSL handshake with remote server. Some possible causes (could be others, see underlying error): 
* A certificate with the wrong KeyUsage was used. The keyUsage should be DigitalSignature
* Erroneous configuration of the trust store
* Intermediate network devices interfering with traffic (e.g. proxies)
* An attacker impersonating the server (man in the middle)
* Wrong TLS version. For Java 7, see 'JSSE tuning parameters' at https://blogs.oracle.com/java-platform-group/entry/diagnosing_tls_ssl_and_https for information about enabling the latest TLS versions
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
</pre>

<p>
            <b>root cause</b>
        </p>
        <pre>javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown

```
Vi bruker:
openjdk version "1.8.0_212"
centOS 7.6

Noen som har noen tips eller råd på hvor jeg kan feilsøke? Har både vært i dialog med commfides og difi og begge har henvist meg hit

**Comment by asjafjell** [comment]
Heisann! Jeg foreslår at du tar en kikk i dokumentasjonen vi har lagd angående akkurat dette. Der finner du svaret på hvorfor det ikke fungerer - du bruker sertifikat med feil `KeyUsage`.

**Comment by asjafjell** [comment]
Og lenka må du selvfølgelig også få: [Dokumentasjon](https://signering-docs.readthedocs.io/en/latest/buy-enterprise-certificates.html)

**Comment by tofiksa** [comment]
> Heisann! Jeg foreslår at du tar en kikk i dokumentasjonen vi har lagd angående akkurat dette. Der finner du svaret på hvorfor det ikke fungerer - du bruker sertifikat med feil `KeyUsage`.

jeg har vært innom der og lest at keyusage må være digital signature, da er mitt oppfølgingsspørsmål. Er det forskjell på Key Usage = Digital Signature og Key Usage = DigitalSignature? For da vi bestilte et testsertifikat fra commfides til digitalsignering så fikk vi dette.

**Comment by asjafjell** [comment]
Beklager så mye. Jeg leste feil. Det virker underlig. Jeg tror ikke det er noe forskjell, men akkurat det har nok Commfides mer peiling på enn oss. 

Vet du, @oyvindn noe om dette?

**Comment by oyvindn** [comment]
For Certificate Extension `Key Usage` er  `Digital Signature` og `digitalSignature` er samme sak. Den første er typisk human readable format, mens den siste er navnet på bit-et som settes i KeyUsage-delen av sertifikatet. Se 4.2.1.3 i https://www.ietf.org/rfc/rfc3280.

```
      KeyUsage ::= BIT STRING {
           digitalSignature        (0),
           nonRepudiation          (1),
           keyEncipherment         (2),
           dataEncipherment        (3),
           keyAgreement            (4),
           keyCertSign             (5),
           cRLSign                 (6),
           encipherOnly            (7),
           decipherOnly            (8) }
```

Jeg tror feilmeldingen dere får i dette tilfelle er veldig misvisende, og tar jeg ikke helt feil er nok problemet at test-sertifikatet er utstedt av feil intermediate CA. Jeg er usikker på grunnen, men Commfides test-virksomhetssertifikater må utstedes fra et intermediate-sertifikat som har CN=Commfides CPN Enterprise-Norwegian SHA256 CA - TEST2. Jeg ser at det sertifikatet dere benytter har CN=Commfides CPN Enterprise-Norwegian SHA256 CA - TEST.

**Comment by asjafjell** [comment]
Jeg har lagt til [ny dokumentasjon](https://signering-docs.readthedocs.io/en/latest/buy-enterprise-certificates.html) for dette nå.

**Comment by tofiksa** [comment]
takker, det funket med nytt sertifikat fra commfides og veldig bra at dokumentasjonen nå spesifiserer TEST2 i sertifikatet fra commfides

**Comment by ivarref** [comment]
Takk for denne informasjonen. Eg (me) hadde samme problemet i går. 
Kunne det vore mogleg å enten støtte '...TEST'-CN-en? Eller gje ei betre feilmelding?
