### ISSUE TITLE
Signering med Safari fungerer ikke i på difitest.signering.posten.no

### ISSUE THREAD

**Issue by erlendfg** [digipost/signature-api-client-java#125]
# Preconditions

Signering i testmiljøet med Safari som nettleser. Versjon 4.6 av klientbiblioteket.

# Description

Siden oktober 2018 har det ikke vært mulig å opprette signeringsoppdrag i testmiljøet med Safari som nettleser (gjelder iOS og MacOSX). Vi får feilmeldingen «The documents are not available». I følge Difi klarte dere å reprodusere feilen i november 2018. De skrev 6.11.2018 til oss: «Den skjer i en flyt som kontrolleres av en underleverandør. De er i dialog med dem for å få ordnet denne bug'en.»

Denne feilen er fortsatt ikke løst i versjon 4.6 av klientbiblioteket. Flyten vår er som følger:

1. Respondenten leverer et spørreskjema og klienten sender JSON til backend.

2. Backend generer PDF og følgende kode blir kjørt som returnerer
redirect-url:

``` java
DirectJobResponse response = null;
DirectSigner.Builder builder = DirectSigner.withPersonalIdentificationNumber(nationalIdNumberLabel);
RespondentGroup respondentGroup = delivery.getForm().getRespondentGroup();
if (respondentGroup.requiresSigningWithLevel3()) {
  DirectSigner signer =
builder.withSignatureType(SignatureType.AUTHENTICATED_SIGNATURE).build();
  response = directClient.create(createJob(signer, createDocument(bytes,
delivery.getForm()), delivery, AuthenticationLevel.THREE));
} else if (respondentGroup.requiresSigningWithLevel4()) {
  DirectSigner signer =
builder.withSignatureType(SignatureType.ADVANCED_SIGNATURE).build();
  response = directClient.create(createJob(signer,
  createDocument(bytes, delivery.getForm()), delivery,
AuthenticationLevel.FOUR));
} else {
  throw new IllegalStateException("Illegal respondent group for signing:
" + respondentGroup.getMessageKey());
}

session.setAttribute(SIGNING_STATUS_PARAM, response.getStatusUrl());
addSubmissionSignatureToSubmission(delivery.getSubmission());
return response.getRedirectUrls().getFor(nationalIdNumberLabel);
```

3. Den redirect-url-en som returneres til frontend bruker vi til å
videresende respondenten til Signeringstjenesten, men i JavaScript
ettersom backend stort sett leverer og mottar JSON:

```
if (data.signingRedirectUrl) {
  window.location = data.signingRedirectUrl;
  return;
}
```

**Comment by PetterSa** [comment]
Dette er et kjent problem i testmiljøer som oppstår fordi oppsettet for URLer ikke er det samme i testmiljøer som i prod. 

Men det finnes en work-around som gjør at korrekte cookies settes for en Safari-browser. Det varierer litt på hvilken type signering du bruker, men det viktige er å få åpnet dokumentet i ett eget vindu istedenfor i en iframe i vår portal. Med avansert signering vil du bli spurt om å åpne PDFen i eget vindu. Hvis det åpnes i eget vindu kan det muligens feile første ganen, men prøv igjen og da vil det fungere. Dette vil også fikse problemet for alle andre signeringer. For andre typer signering, hvor PDFen ikke åpnes i nytt vindu, kan dere hente linken fra iframen på nettsiden og åpne denne i eget vindu og deretter vil det fungere for alle andre signaturer i fremtiden.

Hvis du er en privat avsender (ikke offentlig) så vil du ha mulighet til å velge bank-id eller bank-id på mobil. Hvis du velger vanlig bank-id vil du åpne dokumentet i nytt vindu og dermed få satt de korrekte cookiene i safari. Hvis du prøver å åpne dokumentet igjen vil det virke, og det vil også virke for alle andre signeringer i safari.

En fiks på dette vil nok ta litt tid å utvikle. Siden dette også er et problem bare for safari, bare i testmiljøer, og det har en work-around, er det ikke sikkert det vil prioriteres høyt. Vår anbefaling er å ikke bruke safari i testmiljøer :)

**Comment by erlendfg** [comment]
@PetterSa, grunnen til at vi har brukt Safari i testmiljøet er for å debugge et annet problem vi har med Safari. Produksjonsloggene våre fylles med følgende flere ganger om dagen, og skjer når noen forsøker å signere med denne nettleseren (om det kun skjer med iOS, vet vi ikke):

`userAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1, javax.ws.rs.ProcessingException: URI is not absolute`

**Comment by PetterSa** [comment]
@erlendfg 
Hvis dere debugger et problem har dere kanskje en grei kontroll over hvem som bruker safari? I så tilfelle kan dere muligens be de implementere work-arounden. Den trengs bare å gjøres en gang per installasjon av safari (med mindre dere sletter cookies). Det skal holde å velge BankID (ikke på mobil), fremprovosere feilen, trykke på "Forrige steg" og prøve på nytt med enten BankID eller BankID på mobil.

**Comment by erlendfg** [comment]
BankID på mobil fungerer uansett ikke i testmiljøet, i hvert fall ikke som jeg vet. Vi bruker den kjente testbrukeren som slutter på «574».  Det er ingen iframes inne i bildet før feilmeldingen dukker opp. Ettersom vi har en SSO, får vi ikke valgt autentiseringsform i det hele tatt. Det ble valgt i et tidligere steg _før_ vårt eget spørreskjema vises og som etter utfylling av respondenten blir gjort om til en PDF som sendes Signeringsportalen (signeringsoppdrag). Dermed har jeg ikke muligheten til å gjøre disse tilpasningene du viser til. Feilen skjer på en side hvor frames ikke brukes:
https://difitest.signering.posten.no/signere/#/-/******/dokument

Det er mulig vi bare må lukke vår egen sak rundt feilmeldingen «javax.ws.rs.ProcessingException: URI is not absolute» hvis det ikke er mulig å reprodusere denne i testmiljøet. Med mindre vi legger ut en versjon i produksjonsmiljøet som logger mye rundt dette, noe vi helst ikke ønsker. Men hvis dere kjenner til problemet rundt den feilmeldingen og kan gi oss en forklaring på hvorfor det skjer og om det eventuelt vil bli løst, kan vi også lukke vår egen sak.

Om noen av dere dukker opp i Lillehammer på Brukerrådet neste uke, kan jeg demonstrere problemet.

**Comment by PetterSa** [comment]
Men feilmeldingen ligger i en iframe?
Kunne dere prøve å åpne iframen som har feilmeldingen i et nytt vindu?
Altså da gå inn i browser-inspektoren, finne urlen som ligger iframe elementet, høyreklikke på denne og velge Open in New Tab.

**Comment by erlendfg** [comment]
Got it! Men det ser ikke ut til å hjelpe. Jeg vedlegger et skjermskudd der du ser det både det opprinnelige vinduet og det som er åpnet i ny frame.
<img width="1141" alt="frames-signering" src="https://user-images.githubusercontent.com/50408895/63933497-a58ea580-ca59-11e9-89f3-f03fb7253156.png">

**Comment by PetterSa** [comment]
Oi, det er underlig, for oss pleier det å virke fint da. Dere har cookies skrudd på og slikt? Ikke noe `Block all cookies` eller noe i den duren?
<img width="777" alt="Screenshot 2019-08-29 at 12 41 39" src="https://user-images.githubusercontent.com/3524839/63933936-7d537680-ca5a-11e9-9d8b-939fae1ced4e.png">

**Comment by PetterSa** [comment]
Kanskje prøve å skru av `Prevent cross-site scripting` et lite øyeblikk kan få det til å virke? Huske å skru det på igjen etterpå.

**Comment by PetterSa** [comment]
@erlendfg Fikk dere work-arounden til å virke?

**Comment by erlendfg** [comment]
@PetterSa, beklager sen tilbakemelding. Ja, da fungerte det faktisk. Takk for tipset! Jeg skal forsøke å legge inn logging/debugging av feilmeldingen vi opplever og kan eventuelt lage en ny issue her om det er noe vi tror er en feil. Eller oppdatere denne saken i tilfelle feilen ligger i vår kode. Jeg får nok ikke tid til å se mer på dette før fredag.

**Comment by erlendfg** [comment]
@PetterSa, etter at du ga meg en workaround, fant jeg ut hva den andre feilen var (javax.ws.rs.ProcessingException: URI is not absolute). Det er ikke en feil hos dere, men hos oss. Derfor kan denne saken nå lukkes med mindre dere ønsker å ha den åpen frem til Safari-problemene er løst. «URI is not absolute»-feilmeldingen skyldes at vi legger status-URL i sesjonen slik at det er null når feilmeldingen inntreffer (utløpt sesjon).

**Comment by PetterSa** [comment]
@erlendfg Flott at du skriver hva som gikk galt hos dere i tilfelle andre får lignende problem. Jeg slenger på en wontfix tag og stenger denne issuen :)
