### ISSUE TITLE
TLS-tilkobling feiler

### ISSUE THREAD

**Issue by thxmasj** [digipost/signature-api-client-java#15]
Hei,

Jeg har problemer med å få etablert TLS-tilkoblingen til signeringstjenesten -- får følgende feilmelding under handshake: "SSL peer shut down incorrectly". Får samme feil mot begge disse endepunktene:

https://api.difitest.signering.posten.no
https://api.difiqa.signering.posten.no

Jeg benytter dette klientbiblioteket sin DirectClient, og jeg har forsøkt to forskjellige klientsertifikater, med hhv disse utgiverne (Issuer):
```
C=NO,O=Commfides Norge AS - 988 312 495,OU=CPN Enterprise-Norwegian SHA256 CA- TEST2,OU=Commfides Trust Environment(C) 2014 Commfides Norge AS - TEST,CN=Commfides CPN Enterprise-Norwegian SHA256 CA - TEST2
```
```
CN=Buypass Class 3 Test4 CA 3,O=Buypass AS-983163327,C=NO
```
og hhv. disse emnene (Subject):
```
C=NO,ST=Bærum,L=Lysaker,O=Test Virksomhet,OU=Issued By Commfides Enterprise Norwegian SHA256 CA - TEST,OU=Test Sertifikat,SERIALNUMBER=958935420,CN=Test Virksomhet
```
```
SERIALNUMBER=991825827,CN=DIREKTORATET FOR FORVALTNING OG IKT,OU=SDP - meldingsutveksling,O=DIREKTORATET FOR FORVALTNING OG IKT,C=NO
```

Kun Commfides-sertifikatet har Extended Key Usage med TLS Web Client Authentication.

Disse fungerer som virksomhetssertifikater i andre sammenhenger (f.eks. mot Oppslagstjenesten). Fint hvis noen kan kontakte meg ang. dette på thomas.johansen at difi.no.

-Thomas

**Comment by Espenhh** [comment]
Hei,

tror problemet her er at du har benyttet feil URL som rot-URL inn i `ClientConfiguration` i klientbiblioteket. Vi har vært litt for vage på dette i vår dokumentasjon, beklager dette.

Følgende URLer kan benyttes som rot-URL i `ClientConfiguration`:

* https://api.difitest.signering.posten.no/api
* https://api.difiqa.signering.posten.no/api

*(som du ser, så er issuet at du trenger path'en `/api` på slutten. Rot-pathen er reservert for evt. fremtidig dokumentasjon)*

Har nå oppdatert google docs dokumentet "Testmiljøer for DIFI" for å tydeliggjøre dette. En fremtidig versjon av klientbiblioteket vil også forenkle dette ved at man ikke trenger å spesifisere URLene selv, men heller velge miljø via et sett av Enums.

Si fra om dette løser problemene :)

**Comment by thxmasj** [comment]
Hei Espen, takk for rask tilbakemelding!

Jeg får dessverre samme feil med URLene du oppgir.

Dersom du har noen klientsertifikater du vet skal fungere må du gjerne sende meg. Jeg tror jeg benytter en keystore som er hentet fra SDP-avsender-prosjektet her.

Gi meg også gjerne en link til Google Docs-dokumentet du nevner.

**Comment by Espenhh** [comment]
Hvilken Java-versjon kjører du på?

Har du mulighet til å vise meg et utdrag av koden du bruker for å sette opp klientbiblioteket og gjøre kallet?

Google doc'et jeg refererer til er følgende:
https://docs.google.com/document/d/1c98RPwWB2U5rMmNOh0GA2ZxQZhukqsoM_E6M9zknORU/edit?usp=sharing

**Comment by thxmasj** [comment]
Jeg fant et annet Buypass-signert sertifikat som fungerte nå! SHA-1 fingeravtrykket på dette er
```
C1:2E:A9:C0:0B:36:6A:00:16:9D:65:36:25:0F:C8:E7:2D:AB:1F:68
```
Vet du om tjenesten støtter andre sertifikater utstedt til Difi enn dette?

Mot difitest fikk jeg til og med en 200 OK-respons. difiqa ga 500 Internal Server Error, men jeg forstår at dette miljøet ikke er stabilt.

**Comment by Espenhh** [comment]
Tjenesten støtter alle sertifikater som er utstedt av Buypass eller Commfides, og for testmiljøet må du benytte test-sertifikater utstedt av disse. I tillegg må organisasjonsnummeret være registrert som virksomhet for at du skal kunne sende signeringsoppdrag. Difi er allerede registrert med organisasjonsnummer 991825827, så dersom du benytter et testsertifikat utstedt til Difi, så skal det funke. Bra det også gjør det da :)

Det er også forventet at det ikke fungerer mot difiqa.signering.posten.no. Det miljøet har en nyere versjon av backend'en der hele URL-strukturen er endret – derfor vil ikke `1.0-BETA1` av klientbiblioteket fungere. Anbefaler at du kun benytter difitest.signering.posten.no, den vil holde seg stabil helt til vi kommer med en `1.0-BETA2`-versjon av klientbiblioteket.
