### ISSUE TITLE
Problem med bruk av DirectSigner/withCustomIdentifier i testmiljø

### ISSUE THREAD

**Issue by ivarref** [digipost/signature-api-client-java#161]
Hei

Og takk for eit fint bibliotek!

Eg får eit problem når eg forsøker å bruke `DirectSigner/withCustomIdentifier`. Dette gjeld testmiljøet.

Etter å ha signert med testfødselsnummer `24079409207` får eg følgande feilmelding:

```
En feil oppstod under signeringen. Hvis du ønsker, kan du prøve igjen.
```

Denne feilmeldinga kjem kvar gong.

Om eg bytter ut `withCustomIdentifier` med `withPersonalIdentificationNumber`, så verkar signeringa som forventa. Feilen forsvinn altså om eg bytter til `DirectSigner/withPersonalIdentificationNumber`.

Eksempel-URL som hadde denne oppførselen er `https://difitest.signering.posten.no/signere/#/-/UGdQnwBRdXQ2NhNdP7D_5wWbN_mys7qcZ51DBXxi7VU` (i den grad det kan hjelpe dykk å feilsøke).

Gjer eg noko galt? Må ein gjere noko ekstra for å bruke `withCustomIdentifier`? Eventuelt er det noko som må ordnast hjå dykk?

På førehand takk for svar.

Edit: Eg bruker `5.0-RC4`, siste utgåve av biblioteket.

**Comment by ivarref** [comment]
![Screenshot from 2020-05-04 15-30-10](https://user-images.githubusercontent.com/74075/80970901-35bc9000-8e1c-11ea-9fd9-f69b6dd256b8.png)
Slik ser feilmeldinga ut.

**Comment by ivarref** [comment]
Hei igjen 

Har nokon moglegheit for å sjå på dette?

På førehand takk.

CC @runeflobakk

**Comment by simenstoa** [comment]
Hei! Beklager at denne har gått litt under radaren. Skal se på det med en gang. Har du et kodeeksempel på hvordan du bruker `withCustomIdentifier`?

**Comment by simenstoa** [comment]
Har du mulighet til å prøve på nytt?

**Comment by ivarref** [comment]
Takk for det @simenstoa.

Prøvde på nytt no. Same feil som før.

Her er Clojure koden som er i bruk:
```clojure
(defmethod create-direct-signature-job! :default
  [{:esigner/keys [public-url client]}
   {:keys [callbackId subject document-bytes personalIdentificationNumber]}]
  (log/info "start create-direct-signature-job!")
  (let [exit-urls (ExitUrls/of (URI. (str public-url "/esign/ok?id=" callbackId))
                               (URI. (str public-url "/esign/reject?id=" callbackId))
                               (URI. (str public-url "/esign/error?id=" callbackId)))
        ;signers [(-> (DirectSigner/withPersonalIdentificationNumber personalIdentificationNumber) (.build))]
        ; ^^-- dette fungerer, men er kommentert ut for demonstrasjon
        signers [(-> (DirectSigner/withCustomIdentifier "demo") (.build))]
        ; ^^-- dette gjer at signeringsflyten knekker
        document (-> (DirectDocument/builder subject "signeringsoppdrag.pdf" document-bytes) (.build))
        job (-> (DirectJob/builder document exit-urls signers) (.build))
        pending-job ^DirectJobResponse (.create client job)
        status-url (str (.getStatusUrl pending-job))
        redirect-uri (str (.getRedirectUrl (.getSingleSigner pending-job)))]
    (log/info "redirect url is" redirect-uri)
    (log/info "status url is" status-url)
    {:statusUrl   status-url
     :redirectUrl redirect-uri
     :jobId       (str (.getSignatureJobId pending-job))}))
```

Feilen skjer etter at eg trykker signer dokument, taster inn fødselsnummer, personlig passord, engangspassord, får redirect til signicat.com og så kjem feilen.

**Comment by simenstoa** [comment]
@ivarref Vi har testet å signere i `difitest`-miljøet med brukeren med fødselsnummer `24079409207`, og for oss feiler det uansett med denne brukeren. Har du mulighet til å teste med en annen BankID-testbruker?

**Comment by ivarref** [comment]
Takk @simenstoa.

Eg kan teste med to andre fødselsnummer på måndag.

For oss har `24079409207` alltid fungert greitt. Er den knytta til testsertifikatet vårt på noko vis? Fekk oppgitt den (og to andre) i eit e-brev frå Difis fellesløsninger, ser eg.

**Comment by ivarref** [comment]
Hei @simenstoa 

Eg har testa med alle tre testbrukere me har fått oppgitt:

```
Adminbruker: 24079409207 (kan opprette oppdrag, har tilgang til alle oppdrag, kan opprette og redigere brukere)
Saksbehandler: 24079409126 (kan opprette oppdrag, har tilgang til egne oppdrag)
Innbygger som skal signere: 24079409045
```

Desse fekk me oppgitt i ein epostutveksling med Difis fellesløsninger ved Sture Førre.

Alle desse fungerer med bruk av fødselsnummer `(DirectSigner/withPersonalIdentificationNumber personalIdentificationNumber)`. Ingen fungerer med `(DirectSigner/withCustomIdentifier "demo")`.

Orgnummer me sender frå er `971526920` (for test).

Var dette noko til hjelp?

**Comment by simenstoa** [comment]
Takk @ivarref! Da skal jeg grave litt mer. Beklager at det tar tid!

**Comment by ivarref** [comment]
Takk for det ja.

**Comment by simenstoa** [comment]
Vi har nå verifisert at konfigurasjonen er riktig, og fungere i produksjon. Det vi kan se er at det feiler hos vår signeringsleverandør når de forsøker å slå opp navn basert på personnummeret. Vi hører med de om de kan gi en mer spesifikk forklaring, blant annet om hvor dette slåes opp.

**Comment by simenstoa** [comment]
@ivarref her er svaret de ga:

> I dette tilfellet ser ikke testbrukeren ut til å eksistere i infotorg preprod. Om den har fungert tidligere så er det merkelig at den har blitt fjernet, men det burde være mulig å enten bruke en annen bruker eller ta kontakt med infotorg for å se om de ikke kan legge til et navn på den personen. Tror det er bare å ta kontakt med de via skjema her: https://www.infotorg.no/kundeservice

Håper det hjelper!

**Comment by ivarref** [comment]
Takk for det @simenstoa 

Då lurer eg på følgande: er det mogleg å få andre testbrukere (fødselsnummer) me kan bruke for test?

Takk!

**Comment by simenstoa** [comment]
Hei, da tror jeg det beste er å høre med Digdir igjen. Kanskje de også kan sørge for at brukeren du allerede har blir lagt inn i Infotorg også.

> Desse fekk me oppgitt i ein epostutveksling med Difis fellesløsninger ved Sture Førre.

Er det ok for deg om jeg lukker issuet? Beklager igjen at det har tatt litt tid å nøste opp i dette.

**Comment by ivarref** [comment]
Hei igjen @simenstoa 

Me har fått nye testbrukere no frå Digdir (for ei god stund sidan), og dei verkar som forventa.
