### ISSUE TITLE
Lange poll-intervall

### ISSUE THREAD

**Issue by thxmasj** [digipost/signature-api-client-java#19]
Hei igjen,

Jeg tester polling-funksjonaliteten og får TooEagerPollingException som ber meg vente 7-8 minutter til neste gang. Er det mulig å sette intervallet lavere, slik at det er bedre egnet for testing? Jo lavere jo bedre. Jeg benytter APIet på https://api.difitest.signering.posten.no/api.

**Comment by Espenhh** [comment]
Hei,

akkurat nå kan vi ikke stille på dette i testmiljøet `difitest`. Vi har laget funksjonalitet for dette som vi har klart lokalt, og dette vil bli med i neste release til `difitest`. Denne må koordineres litt med Difi og de tjenesteeierene som har begynt integrasjonsprosessen, da det krever at man går over til BETA2 av klientbiblioteker og api-spesifikasjonen. Vi har noen få endringer til vi ønsker å få med i den versjonen, men tenker vi skal klare å få den ut ila. en ukes tid kanskje :)

Akkurat hva vi setter den til da er litt usikkert, det er viktig at vi har en fornuftig verdi slik at man også opplever TooEagerPollingException i testmiljøet (slik at det ikke kommer overraskende på i produksjon). Vi skal ta en diskusjon på det og finne ut av en "gyllen middelvei"

**Comment by thxmasj** [comment]
Jeg tester nå med 1.0-BETA2 av klientbiblioteket mot difiqa, og jeg får fortsatt svært lange poll-intervaller (siste jeg så var 598 sekunder). Hva kom dere fram til her?

**Comment by Espenhh** [comment]
@thxmasj Vi har gjort poll-tiden konfigurerbar, men ikke endret på den enda. Foreslår at vi setter den til 30 sekunder i `difiqa`, mens vi setter den til 10 minutter i `difitest` (da vi ønsker at dette skal være prodlikt).

Vi har planlagt en deploy til `difitest` av BETA2 i morgen (du er ferdig med testingen der da, sant?), så da kan jeg lage en modifisert versjon med 30 sekunders polltid og rulle den ut til `difiqa` samtidig. OK?

**Comment by thxmasj** [comment]
Fott! Ja, difitest kan oppdateres nå. Vil difiqa oppdateres kontinuerlig?

**Comment by Espenhh** [comment]
@thxmasj flott, da oppdaterer vi både `difitest` og `difiqa` i morgen :)

Vi har frem til nå oppdatert `difiqa` oftere enn `difitest`. Når vi går inn i akseptansetest-fasen, så kommer vi til å kommunisere løpende når vi oppdaterer `difiqa`. Mtp. i morgen så tenker jeg at jeg ruller ut BETA2 i begge miljøene i hvert fall (men med 30-sekunders endringen for `difiqa`)

**Comment by Espenhh** [comment]
@thxmasj da har jeg rullet ut en ny versjon til `difiqa` der polling-intervall er satt til 30 sekunder.

Utrullingen av BETA2 til `difitest` gjøres etter lunch :)
