### ISSUE TITLE
Provide better error message when user submits wrong signer url while requesting new redirect url

### ISSUE THREAD

**Issue by norrs** [digipost/signature-api-client-java#199]
# Preconditions

Testmiljø mot difi

https://signering-docs.readthedocs.io/en/latest/client-integration/direct-flow.html#request-new-redirect-url

# Provide better error message when user submits wrong signer url while requesting new redirect url

```kotlin
        val badArgumentForApiSigningUrl =
            URI.create("https://difitest.signering.posten.no/signere/#/-/3i8uFFB4Gbu_Ukrr8kPGQw5lWHcDPEIsMIkINXkwt9E")

        val requestNewRedirectUrl =
            signeringsService.directClient.requestNewRedirectUrl(WithSignerUrl.of(badArgumentForApiSigningUrl))

        println(requestNewRedirectUrl.redirectUrl)
```

If you for some reason submit the erroneously redirect URL instead of the api signing URL), you get "scary" MITM error message: `Could not find correct organization number in server certificate. Make sure hte server URI is correct. Actual certificate: CN=difitest.signering.posten.no . Expected certificate issued to organization number 9984661185 . This could indicate a misconfiguration of the client or server, potentially a man-in-the-middle attack.`

![2021-05-10-14-26-05-window-select](https://user-images.githubusercontent.com/272215/117661405-9e141f00-b19e-11eb-8313-1bc145151bac.png)
(Ignore the "last" line of stacktrace showing listOppdrag - when quicky debugging locally)

It works as it should if you replace `badArgumentForApiSigningUrl` with :

```kotlin
        val existingApiSigningUrl =
            URI.create("https://api.difitest.signering.posten.no/api/919477822/direct/signature-jobs/60807/signers/65279")
```

I wonder if maybe we could detect if provided URL is a `api url` and not a `redirect url` to provide a better error message to the caller?
But the documentation is clear about what is correct. The weird experience is maybe reading some expectations about Posten's organization number in MITM message.

Be free to close the issue if you disagree and it is good enough as it is.

**Comment by simenstoa** [comment]
Thanks for the feedback. Will label this as an enhancement, and see if we are able to prioritise it.
