### ISSUE TITLE
Varsling ved asynkrone oppdrag

### ISSUE THREAD

**Issue by thxmasj** [digipost/signature-api-client-java#20]
Hei,

Jeg sender inn et asynkront oppdrag (portal). Hva skal skje så? Vil signatar varsles vha. Oppslagstjenesten/Kontaktregisteret på e-post eller SMS? Hvilket miljø for Oppslagstjenesten benyttes i såfall av Signaturtjenesten på https://api.difitest.signering.posten.no/api?

**Comment by Espenhh** [comment]
det er planlagt en utvidelse av tjenesten (Opsjon 3) der du kan spesifisere varsling ved innsending av oppdragene, da ved å benytte oppslagstjenesten. Dette er ikke på plass enda, men du kan se en sneak-peak av hvordan det vil se ut i APIene i dette issuet: https://github.com/digipost/signature-api-specification/issues/20

Inntill videre kan du se bort i fra varsling, og bare logge deg rett inn i portalen med fødselsnummeret du benytter for testing (må være en ID-porten testbruker, du har tilgang til det?). Du logger deg inn her: https://difitest.signering.posten.no Du skal da finne oppdraget du sendte inn, slik at du kan signere det der. Da vil du få signeringsinformasjonen tilbake når du poller fra api-klienten.
