### ISSUE TITLE
Prøver å komme i gang med esignering - feil i testmiljø? Test case 1

### ISSUE THREAD

**Issue by norrs** [digipost/signature-api-client-java#200]
# Kom i gang med esignering - test case 1 - er dette feil i testmiljø?

# Description

Lage en signerjobb med 2 signatører, med type `authenticated signature` og på vegne av seg selv. Dokument ønskes stemples med `nin og navn`. 

Signatør nr 1: `val ninFromDifi2= "31038700912" //Ståle Amor`
Signatør nr 2:  `val ninFromSo1 = "26129321406"`
 
Her fungerer "ikke" signerer med test bruker 26129321406, og blir møtt med en feilmelding om at det har oppstått en systemfeil. 

![2021-05-09-20-30-54-window-select](https://user-images.githubusercontent.com/272215/118273942-d4b2a800-b4c4-11eb-86cd-9e2ac7ef06af.png)

Koden ser type slik ut: 

```kotlin

    fun createSignatureJob(signJobId: UUID, pdfDocumentBytes: ByteArray): DirectJob {

        val document: DirectDocument =
            DirectDocument.builder(
                "Subject i DD obj" /* denne vises paa bankid med lenke til dok */,
                "prototype_dokument.pdf",
                pdfDocumentBytes
            ).fileType(
                Document.FileType.PDF
            ).build()


        val exitUrls =
            ExitUrls.of(
                completionUrlTemplate(signJobId),
                rejectionUrlTemplate(signJobId),
                errorUrlTemplate(signJobId)
            )


        return `attachSignersToNewSigningJobExample1 AuthenticatedSignature With PersonalNINAndName`(document, exitUrls, signJobId)
    }

    private fun `attachSignersToNewSigningJobExample1 AuthenticatedSignature With PersonalNINAndName`(
        document: DirectDocument,
        exitUrls: ExitUrls,
        signJobId: UUID
    ): DirectJob {
        val signer = DirectSigner
            .withPersonalIdentificationNumber(ninFromDifi2)
            .withSignatureType(SignatureType.AUTHENTICATED_SIGNATURE)
            .onBehalfOf(OnBehalfOf.SELF)
            .build()
        val signer2 = DirectSigner
            .withPersonalIdentificationNumber(ninFromSo1)
            .withSignatureType(SignatureType.AUTHENTICATED_SIGNATURE)
            .onBehalfOf(OnBehalfOf.SELF)
            .build()
        val directJob =
            DirectJob.builder(document.title + " noe til", document, exitUrls, signer, signer2)
                .retrieveStatusBy(StatusRetrievalMethod.WAIT_FOR_CALLBACK)
                .withDescription("Dette er en description")
                .withReference(signJobId)
                .withIdentifierInSignedDocuments(IdentifierInSignedDocuments.PERSONAL_IDENTIFICATION_NUMBER_AND_NAME)
                .build()
        return directJob
    }

...

Jobben blir så opprettet med `directClient.create(job)` (`no.digipost.signature.client.direct.DirectClient#create`) hvor `job` er DirectJob objektet vi lager ovenfor. 

```

```kotlin
    val ninFromSo1 = "26129321406"
    val ninFromDifi2= "31038700912" //Ståle Amor
```

`SO` (samordna opptak) har vel fått denne bankid brukeren generert av Difi ved en tidligere anledning i forbindelse med lasttesting mot deres systemer mot ID-porten. 

Her er video hvor jeg viser koden og feilmelding i praksis:

https://unitdir-my.sharepoint.com/:v:/g/personal/rono_unit_no/Ef2ZG445Y0VPoEy_FEHYrMMB1OjftiFYtQETN9tlrlbWEw?e=MRrHxq

(Merk dette er kode rablet ned i full fart bare for å bli kjent med tjenesten, og er vel lik den du finner i dokumentasjonen)

> Lurer på om det er `SO` bruker ikke kan benyttes i dette testmiljøet selv om de går mot `idporten-ver.difi.no` ? 

Nei, den fungerer, se nedenfor .. (svar kom til underveis i issue skriving..)

> Feilsøking på egen hånd: 

Jeg ser også i etterkant av opptak av videoen, at når jeg besøker `brukerprofil-ver1.difi.no`, så dukker det faktisk opp NIN fra den første brukeren jeg signerte med. 

Er dette noe skomt sikkerhetsissue at den husker hvem som signerte første gangen, så når jeg åpner lenke nr 2 for bruker2, så er den fremdeles innlogget som bruker nr 1? 

Det er vel noe uheldig om person1 og person2 benytter samme PC og skal signere dokumentet. 

Jeg fikk demoen til å fungere om jeg besøke `brukerprofil-ver1.difi.no` og logget ut etter første personen hadde signert. 

 EDIT: Fjernet personnummer som ikke var i bruk, og bare var unødvendig informasjon.

**Comment by norrs** [comment]
Videoen var dessverre noe for stor til at jeg kunne legge den til direkte her i github :(  (15mb)

**Comment by simenstoa** [comment]
Hei! Som du sier kan det oppstå feil under signering med id-porten når du bruker samme PC, og ut fra feilmelding ser det ut som den type feil, og ikke en feil med integrasjonen din. Hvis du har adressert på fødselsnummer vil vi sjekke at det er riktig person som har signert etter at signaturen er gjennomført.

**Comment by norrs** [comment]
>>Er dette noe skomt sikkerhetsissue at den husker hvem som signerte første gangen, så når jeg åpner lenke nr 2 for bruker2, så er den fremdeles innlogget som bruker nr 1?

>Det er vel noe uheldig om person1 og person2 benytter samme PC og skal signere dokumentet.

Da noterer jeg ned at vi må alltid teste signering prosessen i forskjellige nettleserprofiler under testingen vår, da det virker som sesjonsopprydding ikke blir gjort ordentlig.

For løsningen bør vel egentlig ikke beholde en "single sign on" fra BankId etter signert/avbrutt oppdrag?
