### ISSUE TITLE
Prøver å komme i gang med esignering - feil i testmiljø? Test case 2

### ISSUE THREAD

**Issue by norrs** [digipost/signature-api-client-java#201]
# Kom i gang med esignering - test case 2 - er dette feil i testmiljø?

# Description

Lage en signerjobb med 2 signatører, med type `advanced signature` og på vegne av seg selv. Dokument ønskes stemples med `nin og navn`. 

Signatør nr 1: `val ninFromDifi2= "31038700912" //Ståle Amor`
Signatør nr 2:  `val ninFromSo1 = "26129321406"`
 
 Her fungerer "ingen" av testbrukerne og jeg blir møtt med en `permission denied` fra jersey:
 
 
![2021-05-09-20-17-50-window-select](https://user-images.githubusercontent.com/272215/118278252-185be080-b4ca-11eb-815b-0b622060ef0a.png)

Koden ser type slik ut: 

```kotlin

    fun createSignatureJob(signJobId: UUID, pdfDocumentBytes: ByteArray): DirectJob {

        val document: DirectDocument =
            DirectDocument.builder(
                "Subject i DD obj" /* denne vises paa bankid med lenke til dok */,
                "prototype_dokument.pdf",
                pdfDocumentBytes
            ).fileType(
                Document.FileType.PDF
            ).build()


        val exitUrls =
            ExitUrls.of(
                completionUrlTemplate(signJobId),
                rejectionUrlTemplate(signJobId),
                errorUrlTemplate(signJobId)
            )


        return `attachSignersToNewSigningJobExample2 AdvancedSigning With PersonalNINAndName`(document, exitUrls, signJobId)
    }

    private fun `attachSignersToNewSigningJobExample2 AdvancedSigning With PersonalNINAndName`(
        document: DirectDocument,
        exitUrls: ExitUrls,
        signJobId: UUID
    ): DirectJob {
        val signer = DirectSigner
            .withPersonalIdentificationNumber(ninFromDifi2)
            .withSignatureType(SignatureType.ADVANCED_SIGNATURE)
            .onBehalfOf(OnBehalfOf.SELF)
            .build()
        val signer2 = DirectSigner
            .withPersonalIdentificationNumber(ninFromSo1)
            .withSignatureType(SignatureType.ADVANCED_SIGNATURE)
            .onBehalfOf(OnBehalfOf.SELF)
            .build()
        val directJob =
            DirectJob.builder(document.title + " noe til", document, exitUrls, signer, signer2)
                .retrieveStatusBy(StatusRetrievalMethod.WAIT_FOR_CALLBACK)
                .withDescription("Dette er en description")
                .withReference(signJobId)
                .withIdentifierInSignedDocuments(IdentifierInSignedDocuments.PERSONAL_IDENTIFICATION_NUMBER_AND_NAME)
                .build()
        return directJob
    }
```

Jobben blir så opprettet med `directClient.create(job)` (`no.digipost.signature.client.direct.DirectClient#create`) hvor `job` er DirectJob objektet vi lager ovenfor. 

Konstanter(national identity numbers) fra koden:
```
    val ninFromSo1 = "26129321406"
    val ninFromDifi2= "31038700912" //Ståle Amor
```

Her er video hvor jeg viser koden og feilmelding i praksis:

https://unitdir-my.sharepoint.com/:v:/g/personal/rono_unit_no/EVyeOki0O2NHl5Ig6qM1tuYBIeBMhY2NLFamD38QzLMSjA?e=vkQ3Cq

(Merk dette er kode rablet ned i full fart bare for å bli kjent med tjenesten, og er vel lik den du finner i dokumentasjonen)

> Feilsøking på egen hånd: 

Etter erfaring fra feilsøking i #200 , så har jeg prøvd testcasen på nytt, og tatt ekstraveien innom `brukerprofil-ver1.difi.no` for å logge ut osv, uten at dette hjalp noe. 

Synes det er spesielt at jeg ikke trenger å skrive inn fødselsnummer (nin) når jeg besøker `redirectUrl`. 

Jeg har også testet med Incognito mode og "Guest user" i Chrome, begge får feilmeldinger, men "Incognito mode" får en annen type feilmelding om at ressursen er borte vekk: 

![2021-05-14-15-41-47-window-select](https://user-images.githubusercontent.com/272215/118282063-2c094600-b4ce-11eb-9b33-7fbba9527812.png)

**Jeg tok så å testet dette i firefox ... og da fikk jeg gjort signering for begge brukerne ...**

Jeg lurer også på hva regler det ligger i bunn for at du skulle åpne lenka på nytt (redirecturl) om du ikke har fullført/startet signering og ikke avbrutt signering, for det fungerte dårlig på kryss av nettlesere. Mistenker denne blir låst til første nettleser som åpner `redirect url` med noen hemmeligheter fra cookie eller local storage. Noe forvirrende når siden gir hint om at du kan fortsette senere:

![2021-05-14-16-09-20-window-select](https://user-images.githubusercontent.com/272215/118282639-c8334d00-b4ce-11eb-91aa-a414533e1f96.png)

**Comment by simenstoa** [comment]
Hei! Vi er kjent med at det er problemer med å signere i test-miljøet i Chrome og Safari med avansert signatur, men at det fungerer i Firefox. Vi jobber med å få fikset dette, og beklager ulempene dette har medført.

En `redirectUrl` kan bare brukes en gang. Hvis undertegner har lyst til å "signere senere" må dere hente en ny `redirectUrl` 
 som undertegner kan sendes til. Så hintet om at du kan signere senere er ment for sluttbruker, som ikke har noe forhold til den spesifikke url'en, siden de bare sendes dit fra en annen nettside/system.

Var det svar på spørsmålene dine? 😊

**Comment by simenstoa** [comment]
@norrs feilen med signeringer i testmiljøet for Safari og Chrome er fikset nå 😊

**Comment by norrs** [comment]
Kan bekrefte at det fungerte i Chrome nå. :+1:
