### ISSUE TITLE
SEID 2.0 støtte?

### ISSUE THREAD

**Issue by ivarref** [digipost/signature-api-client-java#202]
Hei

Og takk for eit bra bibliotek!

Eg har lest litt om den nye sertifikatstandarden SEID 2.0 i [computerworld](https://www.cw.no/artikkel/it-sikkerhet/bytt-til-ny-standard-virksomhetssertifikater), [commfides](https://www.commfides.com/informasjon-om-seid-v2-0/) og [buypass](https://www.buypass.no/ressurser/fagartikler/seid-2-0), og har to spørsmål.

1. Slik eg forstår dette, vil gamle sertifikat verke fram til dei utløper, i lengste fall medio 2025.
Er dette riktig forstått?

2. Støtter dette biblioteket denne nye standarden når ein nyttar java 11?
Om ikkje, kva lyt ein gjera?

På førehand takk for svar
Venleg helsing
Ivar Refsdal

**Comment by simenstoa** [comment]
Hei! 

Jeg skal undersøke litt, så kommer vi tilbake med et svar om ikke altfor lenge.

Mvh Simen

**Comment by runeflobakk** [comment]
Hei @ivarref 
Beklager litt sen respons her. Kommer av sommeravvikling, og de typiske workload-relaterte årsakene 😅 

1. Gamle sertifikater vil virke i vårt API på vanlig måte, altså til de utløper på vanlig måte eller ev. mot formodning blir revokerte av utsteder (Buypass el. Commfides). Vi kommer altså ikke til å fjerne støtte for "gamle" virksomhetssertifikater, men utvide så vi støtter SEID 2.0-virksomhetssertifikater _i tillegg_ til det vi støtter fra før.
2. Dette biblioteket (samt [.NET-varianten](https://github.com/digipost/signature-api-client-dotnet)) vil støtte ny standard på Java 1. Og med mindre det er noe jeg ikke vet på nåværende tidspunkt vil det også støtte ny standard helt ned til Java 8, da det er minimumsversjonen biblioteket skal støtte.

Håper dette gir litt ro i sjelen inntil videre 😄

**Comment by ivarref** [comment]
Takker for dette @runeflobakk 

Då lukker eg denne saka.
