### ISSUE TITLE
Sender kan ikke spesifiseres per forespørsel

### ISSUE THREAD

**Issue by thxmasj** [digipost/signature-api-client-java#23]
Så vidt jeg kan se så kan "sender"-verdien kun settes ved konfigurasjon av klienten (i ClientConfiguration-klassen). Det er et krav at denne kan spesifiseres per forespørsel, så den bør vel da kunne settes på SignatureJob-objektet i forespørselen?

**Comment by aberner** [comment]
Poenget her er at en databehandler vil kunne operere på vegne av flere Behandlingsansvarlige virksomheter og at Sender derfor må kunne endres fra Job til Job.

**Comment by Espenhh** [comment]
Hei,

vi har diskutert dette litt internt, og har ingen store motforestillinger mot å gjøre det på den måten isteden. Vi fikser det slik at det blir med i BETA3 :)
