### ISSUE TITLE
Vertsnavnverifisering er skrudd av

### ISSUE THREAD

**Issue by thxmasj** [digipost/signature-api-client-java#24]
TLS-forbindelsen mellom Java-klient og singeringstjenesten opprettes uten at det utføres vertsnavn-verifisering, noe som medfører en sikkerhetsrisiko.

**Comment by lillesand** [comment]
Det stemmer at vi ikke gjør vertsnavnverifisering. Grunnen til det er at vi bruker to-veis TLS basert på virksomhetssertfikater. Det betyr at vi sjekker organisasjonsnummeret i virksomhetssertifikatet istedet for vertsnavn. Se client-java/blob/master/src/main/java/no/digipost/signature/client/core/internal/PostenEnterpriseCertificateStrategy.java

**Comment by thxmasj** [comment]
Den er god!
