### ISSUE TITLE
Klientbiblioteket må kunne støtte Logging av request og respons 

### ISSUE THREAD

**Issue by aberner** [digipost/signature-api-client-java#25]
Klientbibliotekene må selvsagt støtte at en Avsender/databehandler har behov for å logge requester og responser generert og sendt fra klientbiblioteket.
Dette er viktig i feilsøking og er ofte etterspurt i feilsituasjoner.

Som regel ber Posten at klienten oppgir dette og at alle klienter har kontroll på og forståelse for hva de sender fra seg.

Det er forventet at klientbiblioteket støtter dette på en enkel og dokumentert måte. F.eks. slik det er gjort her: https://github.com/difi/sikker-digital-post-klient-java

**Comment by runeflobakk** [comment]
Enig, dette skal vi få inkludert!

**Comment by runeflobakk** [comment]
Merget til master i #33
