### ISSUE TITLE
Asynkron signering for testbrukere?

### ISSUE THREAD

**Issue by ivarref** [digipost/signature-api-client-java#333]
Hei

Eg freistar å oppretta asynkrone signeringsoppdrag for testbrukere. Testbrukar kjem frå [tenor testdatasøk](https://www.skatteetaten.no/skjema/testdata/). F.eks. har eg nytta fødselsnummer `05837799009`.

Det går tilsynelatande greitt å oppretta eit asynkront signeringsoppdrag for `05837799009`.
Eg får også logga inn på [difitest.signering.posten.no](https://difitest.signering.posten.no/) med dette fødselsnummeret.

Men det dukkar ikkje opp noko asynkront signeringsoppdrag der diverre.

Er dette støtta? Er det mogleg å gjera asynkron signering med testbrukarar frå tenor testdatasøk?

På førehand takk for hjelp!

**Comment by runeflobakk** [comment]
Jeg finner 2 oppdrag i difitest som har 05837799009 som undertegner. Disse oppdragene har feilet fordi vi ikke finner kontaktinformasjon i KRR for varsling (epost og/eller mobilnummer) for testbrukeren. Dette kommer som en statusoppdatering som du har fått når du poller for status i.f.m. asynkrone oppdrag. Jeg ser at status har blitt utlevert og bekreftet mottatt for begge oppdrag, så du skal ha fått [CONTACT_INFORMATION_MISSING](https://github.com/digipost/signature-api-client-java/blob/main/lib/src/main/java/no/digipost/signature/client/portal/SignatureStatus.java#L31-L34) i begge tilfeller.

Har du lagt inn kontaktinformasjon på denne testbrukeren i Tenor?

**Comment by runeflobakk** [comment]
Bra det løste seg!

> Kanskje dette burde inn i dykkar dokumentasjon?

Det er et god ide! Jeg har lagt til en seksjon i kapittelet om adressering av undertegner som henviser til Digdir sine sider

https://signering-docs.readthedocs.io/en/latest/adressering-av-undertegner.html#how-to-use-the-register-in-test-environments
