### ISSUE TITLE
Bruk av statusQueryToken i Java-APIet er vanskelig

### ISSUE THREAD

**Issue by thxmasj** [digipost/signature-api-client-java#34]
Status-URL hentes nå fra `DirectJobResponse` slik:
```java
DirectJobResponse response = ...
String statusUrl = response.getStatusUrl(UUID.randomUUID().toString()).getStatusUrl()
```
Altså må `statusQueryToken` oppgis for å hente ut `statusUrl`, og `statusUrl` vil så inneholde denne.

Problemet er da jeg senere skal hente ut status:
```java
DirectClient client = ...
client.getStatus(new StatusReference(statusUrl, ???));
```
Konstruktøren til `StatusReference` krever altså at jeg oppgir `statusQueryToken` igjen. Dette medfører at jeg må fjerne tokenet fra `statusUrl` først, for deretter å oppgi det til konstruktøren igjen sammen med strippet `statusUrl`.

Jeg forstår at tanken bak dette er at `StatusReference` fra `DirectJobResponse` skal kunne benyttes direkte i `getStatus()`, men dette objektet er ikke serialiserbart slik at det dermed må holdes i heapen mellom kallene (`create()` og `getStatus()`).

**Comment by runeflobakk** [comment]
Det er veldig sant! 
Jeg er midt i en gjennomgang av klientbiblioteket as we speak, og sånn input er veldig nyttig! Skal få fikset det.

Jeg er for meg at jeg eksponerer `statusUrl` direkte fra `DirectJobResponse` slik at man får mulighet til å faktisk persistere tilstanden, før man til slutt kaller `client.getStatus(new StatusReference(statusUrl, statusQueryToken))`. Jeg vil helst slippe å la DirectJobResponse implementere `Serializable`, da det straks medfører litt fordringer rundt vedlikehold av indre klassestruktur, `serialVersionUID`, etc. Høres dette greit ut?

Noen (les: undertegnede) har åpenbart vært litt for "smart" når de har kodet akkurat dette rundt `statusQueryToken`.

**Comment by thxmasj** [comment]
Løsningen fungerer fint, takk!
