### ISSUE TITLE
Eksponer X-Next-permitted-poll-time i NO_UPDATED_STATUS-objekt

### ISSUE THREAD

**Issue by ivarref** [digipost/signature-api-client-java#60]
Hei, og takk for et nyttig bibliotek!

I [dokumentasjonen](http://digipost.github.io/signature-api-client-java/v3.x/#get-status-changes) står det at 

> If the queue is empty (i.e. no jobs have changed status since last poll), you are not allowed to poll again for a defined period. Refer to the API specification to see how long this period is.

(Her er det forøvrig feil lenke til [API-spesifikasjonen](https://github.com/digipost/signature-api-specification/blob/master/integrasjon/asynkron.md#hvor-ofte-skal-du-polle).)

I API-spesifikasjonen står det følgende: 

> Når du gjør denne pollingen så vil du alltid få en HTTP-header (X-Next-permitted-poll-time) som respons som forteller deg når du kan gjøre neste polling. 

Slik jeg skjønner [koden](https://github.com/digipost/signature-api-client-java/blob/850a2dc4f76bdfe147269bf72c7b009644b88496/src/main/java/no/digipost/signature/client/core/internal/ClientHelper.java#L165) så kaster man vekk `X-Next-permitted-poll-time` når man returnerer `null/NO_UPDATED_STATUS`. Dermed blir man faktisk nødt til å gjøre en umiddelbar ny polling for å få vite når man egentlig burde gjøre neste polling.

Tar jeg feil eller har jeg oversett noe? Dette virker som en i overkant upraktisk måte å gjøre ting på.
Er det mulig å få inn `X-Next-permitted-poll-time` i `NO_UPDATED_STATUS` i f.eks. form av en `Instant`?

Takk for svar.

**Comment by SindreNordbo** [comment]
Hei,

takk for tilbakemeldingen. Det ser ut som resonnementet ditt er helt riktig, dette virker litt upraktisk :) Skal se om vi kan få inn tidspunktet i `NO_UPDATED_STATUS`.

Takk for at du melder fra om feil i dokumentasjonen og, det skal vi få fiksa opp i!

**Comment by ivarref** [comment]
Hallo, og takk for det.

Har det skjedd noe arbeid på denne? Det ville vært flott med en ny release som støtter dette.

**Comment by SindreNordbo** [comment]
Planlegger å se på dette i løpet av dagen. Forhåpentligvis kan vi få ut en ny release som støtter dette i løpet av uken med mindre noe uforutsett oppstår.

**Comment by ivarref** [comment]
Supert.

**Comment by SindreNordbo** [comment]
Løst i versjon 4.0. Den blir tilgjengelig på maven central i løpet av en times tid.
